### ISSUE TITLE
How to wire dual Y motors?

### ISSUE THREAD

**Issue by indexdb** [MZachmann/MZ-PickAndPlace#2]
Could you te me how to wire dual Y motors?
Using two drivers or just connect two stepper motors in parallel ?

**Comment by MZachmann** [comment]
The best approach is to have two drivers, one driver per motor and then the two are driven identically in software. 

Never drive two motors in parallel. Motor power is based on current flow and if the two motors don't have identical impedance they won't have the same current flow. 

Running them in series is better but still not great because among other things they then have 1/2 the driving voltage so much less torque.
